# Let's start on the basics. Variables and arrays

### First, import some libraries

In [26]:
import numpy as np
import random
np.random.seed(5)#seed es la semilla para que siempre dos de los mismos valores

In [14]:
array_1 = np.array([5,7,2,15,6,1,9])# Create an array of N values
print(type(array_1), array_1.dtype) #clase a la que pertenece y tipo de dato que almacena

<class 'numpy.ndarray'> int64


In [27]:
array_2 = np.array(np.random.randint(0,10,len(array_1)))# Create an array of random int values
            # with the same lenght as array_1

print(array_1,array_2) # print both array_1 and array_2
print(array_1.shape,array_2.shape) # print both array_1 and array_2 shapes
print(array_1 + array_2) # print summation of array_1 and array_2

[ 5  7  2 15  6  1  9] [3 6 6 0 9 8 4]
(7,) (7,)
[ 8 13  8 15 15  9 13]


In [28]:
array_1[3]=70 # Replace the value of array_1 in pos 3 by 70
print(array_1 + array_2) # Print summation again

[ 8 13  8 70 15  9 13]


In [29]:
# array_1[1] = 32 # Replace the values of array_1 in pos 1-3 by 32
# array_1[2] = 32
# array_1[3] = 32
array_1[1:3] = 32
print (array_1 + array_2) # Print summation again

[ 8 38 38 70 15  9 13]


In [30]:
array_3 = array_1 * array_2 # Apply element-wise multiplication among array_1 and array_2
print(array_3) # Print results

[ 15 192 192   0  54   8  36]


# Playing with some images! Introduction to OpenCV

Download the image [lena.jpg](https://drive.google.com/file/d/1gH5sJN__2g7f9ndLhLvTECdOBJIGUbg_/view) before getting started!


### First, let's mount Google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

### Import some libraries

In [ ]:
# Import some libraries
import numpy as np
import cv2
import matplotlib.pyplot as plt

## Load an image using OpenCV

In [ ]:
# Loading a color image
img = cv2.imread( _ )
_
plt.imshow(img) # plots an image

### Let's play with the data

In [ ]:
# Printing the image shape (size of the image)
_

In [ ]:
# Looking through the image...
# print among image indexes


In [ ]:
# Changing its channels values!
img = cv2.imread( _ )
_
plt.imshow(img) # Voila!

### Load an image in grayscale

In [ ]:
# Loading a color image in grayscale
img_gray = cv2.imread( _ )
plt.imshow(img_gray, _ )

### Play with the image


In [ ]:
# Printing the image shape
_

In [ ]:
# Regarding through the image... Again


### Going further

In [ ]:
# Messing everything around.
img = cv2.imread( _ )
_
plt.imshow(img_gray, _ )

In [ ]:
# Playing with image intensities
img_gray = cv2.imread( _ )

for r in _  :  # Go through rows
  for c in _ : # Go through cols
    if _ : # Create a simple condition
      _ # Do something

plt.imshow(img_gray, _ )

### Save an image using OpenCV

In [ ]:
cv2.imwrite('newlena.png',img_gray)

### Crop the image - taking regions of interest (ROI)

In [ ]:
# Extract some ROI
roi = _
plt.imshow(roi, _ )

In [ ]:
img_gray[ _ , _ ] = roi
plt.imshow(img_gray, _ )

## Load an image using pillow (PIL)

In [ ]:
from PIL import Image

In [ ]:
# Loading a color image
img = Image.open( _ )
plt.imshow(img) # plots an image

In [ ]:
print (img[:10, :10]) ## Error. This is not an array

In [ ]:
img = np.asarray( _ ) ## Convert to an array
print (img[ _ , _ ]) ## Now it works!
print (img.shape)

### Load the image in grayscale

In [ ]:
img = Image.open( _ ).convert("L")
plt.imshow(img, _ ) # plots an image